// src/lib/address.test.ts
//
// Tests for Dash address classification on the POS Admin screen. Run with:
//   node --test src/lib/address.test.ts
//
// Every concrete address below is CHECKSUM-VALID and was generated by an
// independent script, not copied by eye:
//
//   - L1 Core addresses encode version byte || 20-byte hash || first 4 bytes of
//     double-SHA256 (base58check). The all-zero and all-0xff hash cases
//     reproduce the exact strings published in
//     dashpoint-api/docs/dash-address-classification.md, which is itself
//     grounded in an exhaustive enumeration of the leading-character space.
//   - L2 Platform addresses are bech32m with HRP dash/tdash and a type byte.
//     The Orchard case is the verified real address from the same spec, which
//     round-tripped through dpp with --features shielded-client.
//
// crypto.subtle is a global in Node 20+, so the module under test runs here
// exactly as the browser runs it.

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { classifyDashAddress } from './address.ts'

/* --- L1 Core, from the spec's exhaustive enumeration --- */
const CORE_MAIN_P2PKH = 'XagqqFetxiDb9wbartKDrXgnqLah6SqX2S'
const CORE_MAIN_P2PKH_FF = 'Xz2SpMxBftgTyNjftJeYLexaTqqdgzkiPj'
const CORE_MAIN_P2SH = '7SQekjmcMtR25wEPPiL6m1Mb5586R5ut33'
const CORE_MAIN_P2SH_FF = '7qkFjr4u54stuNNUR8fRF8dNhaP35twQaY'
const CORE_TEST_P2PKH = 'yLKSrCjLQFsfVgX8RjdctZ797d54atPjnV'
const CORE_TEST_P2SH = '8eRTi4fUVRoeYEeeTyL4DPAwxatvbjaxFV'

/* --- L2 Platform shielded, the verified real round-trip from the spec --- */
const PLATFORM_SHIELDED_MAIN =
    'dash1zry9ejypaadw9s2z6zl402muazxpdj9f7rrtf47m6r2ezzz784u995e8hhl9zfrjd86p7ycep3uxn'
const PLATFORM_SHIELDED_TEST =
    'tdash1zry9ejypaadw9s2z6zl402muazxpdj9f7rrtf47m6r2ezzz784u995e8hhl9zfrjd86p7ycfud8u2'

/* --- L2 Platform transparent, generated (all-zero 20-byte hash) --- */
const PLATFORM_P2PKH_MAIN = 'dash1kqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq6cjeng'
const PLATFORM_P2SH_MAIN = 'dash1sqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqhrusmy'
const PLATFORM_P2PKH_TEST = 'tdash1kqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq2lp8zx'
const PLATFORM_P2SH_TEST = 'tdash1sqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8y0w22'

/* The address the old Admin screen was built around: the NEAR Intents Dash
 * treasury, cited in config.ts. It must keep classifying as a valid mainnet
 * P2PKH, because it is what the merchant-facing copy refers to. */
const KEEP_WORKING_TREASURY = 'XxA9DbXaFpF4GFY8KUNX7eAxhZPsWtcKhc'

test('classifies the mainnet P2PKH address the Admin screen was built around', async () => {
    const r = await classifyDashAddress(KEEP_WORKING_TREASURY)

    assert.equal(r.kind, 'core-p2pkh')
    assert.equal(r.layer, 'L1')
    assert.equal(r.network, 'mainnet')
    assert.equal(r.shielded, false)
})

test('classifies mainnet L1 Core P2PKH and P2SH', async () => {
    const p2pkh = await classifyDashAddress(CORE_MAIN_P2PKH)
    assert.equal(p2pkh.kind, 'core-p2pkh')
    assert.equal(p2pkh.layer, 'L1')
    assert.equal(p2pkh.network, 'mainnet')
    assert.equal(p2pkh.shielded, false)

    const p2sh = await classifyDashAddress(CORE_MAIN_P2SH)
    assert.equal(p2sh.kind, 'core-p2sh')
    assert.equal(p2sh.layer, 'L1')
    assert.equal(p2sh.network, 'mainnet')
    assert.equal(p2sh.shielded, false)
})

test('classifies both extremes of each L1 hash space', async () => {
    for (const input of [CORE_MAIN_P2PKH, CORE_MAIN_P2PKH_FF]) {
        assert.equal((await classifyDashAddress(input)).kind, 'core-p2pkh')
    }

    for (const input of [CORE_MAIN_P2SH, CORE_MAIN_P2SH_FF]) {
        assert.equal((await classifyDashAddress(input)).kind, 'core-p2sh')
    }
})

test('classifies L1 testnet addresses and marks the network as ambiguous', async () => {
    const p2pkh = await classifyDashAddress(CORE_TEST_P2PKH)
    const p2sh = await classifyDashAddress(CORE_TEST_P2SH)

    assert.equal(p2pkh.kind, 'core-p2pkh')
    assert.equal(p2sh.kind, 'core-p2sh')

    /*
     * Testnet, Devnet and Regtest share version bytes, so the UI must not
     * claim to know which one this is.
     */
    assert.equal(p2pkh.network, 'testnet-or-devnet-or-regtest')
    assert.equal(p2sh.network, 'testnet-or-devnet-or-regtest')
})

test('classifies the L2 Platform shielded (Orchard) address', async () => {
    const main = await classifyDashAddress(PLATFORM_SHIELDED_MAIN)
    assert.equal(main.kind, 'platform-shielded')
    assert.equal(main.layer, 'L2')
    assert.equal(main.network, 'mainnet')
    assert.equal(main.shielded, true)

    const test_ = await classifyDashAddress(PLATFORM_SHIELDED_TEST)
    assert.equal(test_.kind, 'platform-shielded')
    assert.equal(test_.network, 'testnet-or-devnet-or-regtest')
    assert.equal(test_.shielded, true)
})

test('classifies L2 Platform transparent P2PKH and P2SH', async () => {
    const p2pkh = await classifyDashAddress(PLATFORM_P2PKH_MAIN)
    assert.equal(p2pkh.kind, 'platform-p2pkh')
    assert.equal(p2pkh.layer, 'L2')
    assert.equal(p2pkh.shielded, false)

    const p2sh = await classifyDashAddress(PLATFORM_P2SH_MAIN)
    assert.equal(p2sh.kind, 'platform-p2sh')
    assert.equal(p2sh.layer, 'L2')
    assert.equal(p2sh.shielded, false)
})

test('classifies L2 Platform transparent on tdash', async () => {
    assert.equal((await classifyDashAddress(PLATFORM_P2PKH_TEST)).kind, 'platform-p2pkh')
    assert.equal((await classifyDashAddress(PLATFORM_P2SH_TEST)).kind, 'platform-p2sh')
})

test('distinguishes shielded from transparent despite the SHARED HRP', async () => {
    /*
     * This is the whole reason the rule decodes and reads the type byte
     * instead of matching a prefix: all three share `dash1`.
     */
    assert.ok(PLATFORM_SHIELDED_MAIN.startsWith('dash1'))
    assert.ok(PLATFORM_P2PKH_MAIN.startsWith('dash1'))
    assert.ok(PLATFORM_P2SH_MAIN.startsWith('dash1'))

    assert.equal((await classifyDashAddress(PLATFORM_SHIELDED_MAIN)).shielded, true)
    assert.equal((await classifyDashAddress(PLATFORM_P2PKH_MAIN)).shielded, false)
    assert.equal((await classifyDashAddress(PLATFORM_P2SH_MAIN)).shielded, false)
})

test('the three Platform kinds get three DISTINCT labels', async () => {
    const labels = [
        (await classifyDashAddress(PLATFORM_SHIELDED_MAIN)).label,
        (await classifyDashAddress(PLATFORM_P2PKH_MAIN)).label,
        (await classifyDashAddress(PLATFORM_P2SH_MAIN)).label,
    ]

    assert.equal(new Set(labels).size, 3, `labels must differ: ${labels.join(' | ')}`)
})

test('labels never contain the word "invalid" — an unknown address is simply unnamed', async () => {
    /*
     * The regression this module was written to fix: the old UI told a merchant
     * their non-P2PKH Dash address was "Not a valid Dash mainnet P2PKH
     * address." A recognised address must never carry an "invalid" label.
     */
    const recognised = [
        KEEP_WORKING_TREASURY,
        CORE_MAIN_P2SH,
        CORE_TEST_P2PKH,
        PLATFORM_SHIELDED_MAIN,
        PLATFORM_P2PKH_MAIN,
        PLATFORM_P2SH_MAIN,
    ]

    for (const input of recognised) {
        const r = await classifyDashAddress(input)
        assert.ok(r.label.length > 0, `expected a label for ${input}`)
        assert.ok(!/invalid/i.test(r.label), `label must not say invalid: ${r.label}`)
    }
})

test('an unknown address has an EMPTY label, so the caller supplies the wording', async () => {
    const r = await classifyDashAddress('not an address')
    assert.equal(r.kind, 'unknown')
    assert.equal(r.label, '')
})

test('rejects a tampered base58check checksum rather than mislabelling it', async () => {
    /*
     * Flip the final character: the checksum must fail, so this is not a Dash
     * address even though its shape and prefix are right.
     */
    const tampered = CORE_MAIN_P2PKH.slice(0, -1) + 'T'
    const r = await classifyDashAddress(tampered)

    assert.equal(r.kind, 'unknown')
    assert.equal(r.layer, null)
})

test('rejects a bech32 address with an unrecognised type byte', async () => {
    /*
     * `dash1q…` is a valid-shaped bech32m string whose first data character
     * decodes to top-5-bits 0, i.e. a type byte 0x00-0x07 — not a Dash type.
     * Verified to reach the type-byte branch rather than an early length bail.
     */
    const r = await classifyDashAddress('dash1q' + 'q'.repeat(65))
    assert.equal(r.kind, 'unknown')
})

test('rejects a shielded address whose payload length is wrong', async () => {
    /*
     * Type byte right (0x10 -> 'z'), but too short to hold 44 payload bytes.
     * Upstream treats a wrong length as a hard decode error
     * (orchard_address.rs:105-118), so it must not be accepted here either.
     */
    const r = await classifyDashAddress('dash1z' + 'q'.repeat(23))
    assert.equal(r.kind, 'unknown')
})

test('rejects non-Dash strings', async () => {
    const inputs = [
        '',
        '   ',
        'hello world',
        'not an address',
        '0CL7qwbGPi4P6jqhat5pQxzSZ9PPxvNkDU8tU9yXYyzt', // '0' is not base58
        'bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4', // Bitcoin bech32
        '1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2', // Bitcoin base58check (version 0x00)
        '2BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2', // no mainnet Dash address starts with 2
    ]

    for (const input of inputs) {
        const r = await classifyDashAddress(input)
        assert.equal(r.kind, 'unknown', `expected unknown for ${JSON.stringify(input)}`)
        assert.equal(r.shielded, false)
    }
})

test('rejects non-string input without throwing', async () => {
    for (const input of [undefined, null, 12345, {}, [], true]) {
        const r = await classifyDashAddress(input)
        assert.equal(r.kind, 'unknown')
    }
})

test('tolerates surrounding whitespace from a paste', async () => {
    const r = await classifyDashAddress(`  ${PLATFORM_SHIELDED_MAIN}\n`)
    assert.equal(r.kind, 'platform-shielded')
    assert.equal(r.shielded, true)
})

test('rejects mixed-case bech32 instead of normalising it', async () => {
    /*
     * bech32 forbids mixed case. Normalising would silently "fix" a typo, so
     * the classifier must reject.
     */
    const mixed = 'Dash1' + PLATFORM_SHIELDED_MAIN.slice('dash1'.length)
    assert.equal((await classifyDashAddress(mixed)).kind, 'unknown')
})

test('every recognised result carries a layer and a label', async () => {
    const recognised = [
        CORE_MAIN_P2PKH,
        CORE_MAIN_P2SH,
        CORE_TEST_P2PKH,
        CORE_TEST_P2SH,
        PLATFORM_SHIELDED_MAIN,
        PLATFORM_P2PKH_MAIN,
        PLATFORM_P2SH_MAIN,
    ]

    for (const input of recognised) {
        const r = await classifyDashAddress(input)
        assert.notEqual(r.kind, 'unknown', `expected a kind for ${input}`)
        assert.ok(r.label.length > 0, `expected a label for ${input}`)
        assert.ok(r.layer === 'L1' || r.layer === 'L2', `expected a layer for ${input}`)
    }
})

test('shielded is true for exactly one kind', async () => {
    const recognised = [
        CORE_MAIN_P2PKH,
        CORE_MAIN_P2SH,
        CORE_TEST_P2PKH,
        PLATFORM_SHIELDED_MAIN,
        PLATFORM_P2PKH_MAIN,
        PLATFORM_P2SH_MAIN,
    ]

    for (const input of recognised) {
        const r = await classifyDashAddress(input)
        assert.equal(r.shielded, r.kind === 'platform-shielded')
    }
})

test('the local decoder fixes the leading-zero double-count in config.ts', async () => {
    /*
     * `config.ts` decodes a single '1' as TWO bytes because its accumulator
     * starts at 0 and then re-adds the leading zero byte. This module counts
     * the leading '1's first. Both are only reachable via this classifier as
     * "unknown", but the count is asserted so the two decoders do not silently
     * drift back together.
     */
    for (const input of ['1', '11', '111', '1111']) {
        const r = await classifyDashAddress(input)
        assert.equal(r.kind, 'unknown')
    }
})
