// src/lib/address.test.ts
//
// Tests for Dash address classification. Run with:
//   node --test src/lib/address.test.ts
//
// Every concrete address below is CHECKSUM-VALID and was generated by an
// independent script, not copied by eye:
//
//   - L1 Core addresses encode version byte ‖ 20-byte hash ‖ first 4 bytes of
//     double-SHA256 (base58check). The all-zero and all-0xff hash cases
//     reproduce the exact strings published in
//     paymedash-api/docs/dash-address-classification.md, which is itself
//     grounded in an exhaustive enumeration of the leading-character space.
//   - L2 Platform addresses are bech32m with HRP dash/tdash and a type byte.
//     The Orchard case round-trips against the verified real address in the
//     same spec (`dash1zry9ejy...`).
//
// crypto.subtle is available in Node 20+ as a global, which is why the
// classifier can be tested here unchanged from how the Worker runs it.

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { classifyDashAddress } from './address.ts'

/* --- L1 Core, from the spec's exhaustive enumeration --- */
const CORE_MAIN_P2PKH = 'XagqqFetxiDb9wbartKDrXgnqLah6SqX2S'
const CORE_MAIN_P2PKH_FF = 'Xz2SpMxBftgTyNjftJeYLexaTqqdgzkiPj'
const CORE_MAIN_P2SH = '7SQekjmcMtR25wEPPiL6m1Mb5586R5ut33'
const CORE_MAIN_P2SH_FF = '7qkFjr4u54stuNNUR8fRF8dNhaP35twQaY'
const CORE_TEST_P2PKH = 'yLKSrCjLQFsfVgX8RjdctZ797d54atPjnV'
const CORE_TEST_P2SH = '8eRTi4fUVRoeYEeeTyL4DPAwxatvbjaxFV'

/* --- L2 Platform shielded, the verified real round-trip from the spec --- */
const PLATFORM_SHIELDED_MAIN =
    'dash1zry9ejypaadw9s2z6zl402muazxpdj9f7rrtf47m6r2ezzz784u995e8hhl9zfrjd86p7ycep3uxn'
const PLATFORM_SHIELDED_TEST =
    'tdash1zry9ejypaadw9s2z6zl402muazxpdj9f7rrtf47m6r2ezzz784u995e8hhl9zfrjd86p7ycfud8u2'

/* --- L2 Platform transparent, generated (all-zero 20-byte hash) --- */
const PLATFORM_P2PKH_MAIN = 'dash1kqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq6cjeng'
const PLATFORM_P2SH_MAIN = 'dash1sqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqhrusmy'
const PLATFORM_P2PKH_TEST = 'tdash1kqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq2lp8zx'
const PLATFORM_P2SH_TEST = 'tdash1sqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8y0w22'

test('classifies mainnet L1 Core P2PKH', async () => {
    const r = await classifyDashAddress(CORE_MAIN_P2PKH)
    assert.equal(r.kind, 'core-p2pkh')
    assert.equal(r.layer, 'L1')
    assert.equal(r.network, 'mainnet')
    assert.equal(r.shielded, false)
})

test('classifies mainnet L1 Core P2SH', async () => {
    const r = await classifyDashAddress(CORE_MAIN_P2SH)
    assert.equal(r.kind, 'core-p2sh')
    assert.equal(r.layer, 'L1')
    assert.equal(r.network, 'mainnet')
})

test('classifies both extremes of the L1 P2PKH hash space', async () => {
    const lo = await classifyDashAddress(CORE_MAIN_P2PKH)
    const hi = await classifyDashAddress(CORE_MAIN_P2PKH_FF)
    assert.equal(lo.kind, 'core-p2pkh')
    assert.equal(hi.kind, 'core-p2pkh')
    assert.equal(lo.network, 'mainnet')
    assert.equal(hi.network, 'mainnet')
})

test('classifies both extremes of the L1 P2SH hash space', async () => {
    const lo = await classifyDashAddress(CORE_MAIN_P2SH)
    const hi = await classifyDashAddress(CORE_MAIN_P2SH_FF)
    assert.equal(lo.kind, 'core-p2sh')
    assert.equal(hi.kind, 'core-p2sh')
})

test('classifies L1 testnet addresses and marks the network as ambiguous', async () => {
    const p2pkh = await classifyDashAddress(CORE_TEST_P2PKH)
    const p2sh = await classifyDashAddress(CORE_TEST_P2SH)

    assert.equal(p2pkh.kind, 'core-p2pkh')
    assert.equal(p2sh.kind, 'core-p2sh')

    /* Testnet/Devnet/Regtest share version bytes, so the UI must not claim to
     * know which one this is. */
    assert.equal(p2pkh.network, 'testnet-or-devnet-or-regtest')
    assert.equal(p2sh.network, 'testnet-or-devnet-or-regtest')
})

test('classifies the L2 Platform shielded (Orchard) address — the case that matters', async () => {
    const main = await classifyDashAddress(PLATFORM_SHIELDED_MAIN)
    assert.equal(main.kind, 'platform-shielded')
    assert.equal(main.layer, 'L2')
    assert.equal(main.network, 'mainnet')
    assert.equal(main.shielded, true)

    const test_ = await classifyDashAddress(PLATFORM_SHIELDED_TEST)
    assert.equal(test_.kind, 'platform-shielded')
    assert.equal(test_.layer, 'L2')
    assert.equal(test_.network, 'testnet-or-devnet-or-regtest')
    assert.equal(test_.shielded, true)
})

test('classifies L2 Platform transparent P2PKH and P2SH', async () => {
    const p2pkh = await classifyDashAddress(PLATFORM_P2PKH_MAIN)
    assert.equal(p2pkh.kind, 'platform-p2pkh')
    assert.equal(p2pkh.layer, 'L2')
    assert.equal(p2pkh.shielded, false)

    const p2sh = await classifyDashAddress(PLATFORM_P2SH_MAIN)
    assert.equal(p2sh.kind, 'platform-p2sh')
    assert.equal(p2sh.layer, 'L2')
    assert.equal(p2sh.shielded, false)
})

test('classifies L2 Platform transparent on tdash', async () => {
    const p2pkh = await classifyDashAddress(PLATFORM_P2PKH_TEST)
    const p2sh = await classifyDashAddress(PLATFORM_P2SH_TEST)

    assert.equal(p2pkh.kind, 'platform-p2pkh')
    assert.equal(p2sh.kind, 'platform-p2sh')
    assert.equal(p2pkh.network, 'testnet-or-devnet-or-regtest')
})

test('distinguishes shielded from transparent despite the SHARED HRP', async () => {
    /* This is the whole reason the rule decodes and reads the type byte
     * instead of matching a prefix: all three share `dash1`. */
    assert.ok(PLATFORM_SHIELDED_MAIN.startsWith('dash1'))
    assert.ok(PLATFORM_P2PKH_MAIN.startsWith('dash1'))
    assert.ok(PLATFORM_P2SH_MAIN.startsWith('dash1'))

    const shielded = await classifyDashAddress(PLATFORM_SHIELDED_MAIN)
    const p2pkh = await classifyDashAddress(PLATFORM_P2PKH_MAIN)
    const p2sh = await classifyDashAddress(PLATFORM_P2SH_MAIN)

    assert.equal(shielded.shielded, true)
    assert.equal(p2pkh.shielded, false)
    assert.equal(p2sh.shielded, false)
})

test('rejects a tampered base58check checksum rather than mislabelling it', async () => {
    /* Flip the final character: the checksum must fail, so this is not a Dash
     * address even though its shape and prefix are right. */
    const tampered = CORE_MAIN_P2PKH.slice(0, -1) + (CORE_MAIN_P2PKH.endsWith('S') ? 'T' : 'S')
    const r = await classifyDashAddress(tampered)
    assert.equal(r.kind, 'unknown')
    assert.equal(r.layer, null)
})

test('rejects a bech32 address with an unrecognised type byte', async () => {
    /* `dash1q...` is a valid-shaped bech32m string whose first data character
     * decodes to top-5-bits 0, i.e. a type byte 0x00-0x07 — not any Dash type. */
    const r = await classifyDashAddress('dash1q' + 'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq')
    assert.equal(r.kind, 'unknown')
})

test('rejects a shielded address whose payload length is wrong', async () => {
    /* Type byte right (0x10 -> 'z'), but too short to hold 44 payload bytes.
     * Upstream treats a wrong length as a hard decode error
     * (orchard_address.rs:105-118), so it must not be accepted here either. */
    const short = 'dash1zqqqqqqqqqqqqqqqqqqqqqqqqqq'
    const r = await classifyDashAddress(short)
    assert.equal(r.kind, 'unknown')
})

test('rejects non-Dash strings', async () => {
    const inputs = [
        '',
        '   ',
        'hello world',
        'not an address',
        '0CL7qwbGPi4P6jqhat5pQxzSZ9PPxvNkDU8tU9yXYyzt', // '0' is not base58
        'bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4', // Bitcoin bech32
        '1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2', // Bitcoin base58check (version 0x00)
    ]

    for (const input of inputs) {
        const r = await classifyDashAddress(input)
        assert.equal(r.kind, 'unknown', `expected unknown for ${JSON.stringify(input)}`)
        assert.equal(r.shielded, false)
    }
})

test('rejects non-string input without throwing', async () => {
    for (const input of [undefined, null, 12345, {}, [], true]) {
        const r = await classifyDashAddress(input)
        assert.equal(r.kind, 'unknown')
    }
})

test('tolerates surrounding whitespace from a paste', async () => {
    const r = await classifyDashAddress(`  ${PLATFORM_SHIELDED_MAIN}\n`)
    assert.equal(r.kind, 'platform-shielded')
    assert.equal(r.shielded, true)
})

test('rejects mixed-case bech32 instead of normalising it', async () => {
    /* bech32 forbids mixed case. Normalising would silently "fix" a typo, so
     * the classifier must reject. */
    const mixed = 'Dash1' + PLATFORM_SHIELDED_MAIN.slice('dash1'.length)
    const r = await classifyDashAddress(mixed)
    assert.equal(r.kind, 'unknown')
})

test('every non-unknown result carries a non-empty label', async () => {
    const recognised = [
        CORE_MAIN_P2PKH,
        CORE_MAIN_P2SH,
        CORE_TEST_P2PKH,
        CORE_TEST_P2SH,
        PLATFORM_SHIELDED_MAIN,
        PLATFORM_P2PKH_MAIN,
        PLATFORM_P2SH_MAIN,
    ]

    for (const input of recognised) {
        const r = await classifyDashAddress(input)
        assert.notEqual(r.kind, 'unknown', `expected a kind for ${input}`)
        assert.ok(r.label.length > 0, `expected a label for ${input}`)
        assert.ok(r.layer === 'L1' || r.layer === 'L2')
    }
})

test('shielded is true for exactly one kind', async () => {
    const recognised = [
        CORE_MAIN_P2PKH,
        CORE_MAIN_P2SH,
        CORE_TEST_P2PKH,
        PLATFORM_SHIELDED_MAIN,
        PLATFORM_P2PKH_MAIN,
        PLATFORM_P2SH_MAIN,
    ]

    for (const input of recognised) {
        const r = await classifyDashAddress(input)
        assert.equal(r.shielded, r.kind === 'platform-shielded')
    }
})
